apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server-deployment
  namespace: buy-better

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: product-server
          imagePullPolicy: Never
          env:
            - name: WEB_SERVICE_ENV
              value: "cluster-dev"
            - name: DB_DSN # dev local db is not sensitive
              value: "postgresql://postgres:admin1234@host.minikube.internal:5433/buy-better-core?sslmode=disable"
            - name: DB_DRIVER
              value: "postgres"
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"