apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
patches:
  - path: ./dev-service-patch.yml
  - path: ./dev-deployment-patch.yml
images:
  - name: product-server-image
    newName: opplieam/bb-product-server
    newTag: cluster-dev