# DONT FORGET TO UPDATE IMAGE TAG BY --set image.tag=xxx

# Namespace
namespace: buy-better

# Service
service:
  type: ClusterIP
  port: 3031

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
#  targetMemoryUtilizationPercentage: 90

replicaCount: 1

# Container Image
image:
  repository: opplieam/bb-product-server
  pullPolicy: Always
  tag: ""
imagePullSecrets: []

env:
  webService: "prod"
  jaegerEndpoint: "http://host.minikube.internal:14268/api/traces"