apiVersion: v1
kind: Service
metadata:
  namespace: buy-better
  name: product-server-service

spec:
  selector:
    app: product-server
  type: ClusterIP
  ports:
    - name: product-server-cip
      port: 3031
      targetPort: 3031