//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	GroupProduct = GroupProduct.FromSchema(schema)
	ImageProduct = ImageProduct.FromSchema(schema)
	MatchProductGroup = MatchProductGroup.FromSchema(schema)
	PriceNow = PriceNow.FromSchema(schema)
	Products = Products.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	Sellers = Sellers.FromSchema(schema)
	UserSubProduct = UserSubProduct.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
