//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PriceNow struct {
	ID        int32 `sql:"primary_key"`
	Price     float64
	Currency  string
	CreatedAt time.Time
	ProductID int32
}
