//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID        int32 `sql:"primary_key"`
	CreatedAt time.Time
	LoginAt   time.Time
	Email     string
	FirstName *string
	LastName  *string
	Active    bool
	Role      string
}
