apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bb-product-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bb-product-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bb-product-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "bb-product-server.fullname" . }}
      labels: {{- include "bb-product-server.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: WEB_SERVICE_ENV
              value: {{ .Values.env.webService }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: DB_DSN
            - name: DB_DRIVER
              value: "postgres"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.env.jaegerEndpoint }}
