apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-server-deployment
  namespace: buy-better

spec:
  selector:
    matchLabels:
      app: product-server

  template:
    metadata:
      labels:
        app: product-server
    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: product-server
          image: product-server-image
          ports:
            - name: product-port
              containerPort: 3031

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

