name: CI
on:
  workflow_dispatch:
jobs:
  build_images_and_push:
    name: Build docker image and push
    #    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: make docker-build-prod

      - name: Push to Docker hub
        run: make docker-push

      - name: Install helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.15.2'

      - name: Gen manifest
        run: make gen-prod-chart

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ".genmanifest/bb-product-server-chart"
          target-directory: "bb-product-server"
          destination-github-username: "opplieam"
          destination-repository-name: "bb-k8s-infra"
          target-branch: "main"


